### ISSUE TITLE
Unlisted/unsupported Movement Abilities

### ISSUE THREAD

**Issue by Fyrhtu** [emersonrp/bindcontrol#1]
Additional Movement powers not listed/supported - Mystical Flight/ Translocation, Speed of Sound, Infiltration, Mighty Leap.

**Comment by Fyrhtu** [comment]
Also Ninja Run, Athletic Run, Beast Run

**Comment by emersonrp** [comment]
This is indeed overdue.  I'll look at how I can add those most simply, pending a long-needed rethink of how to do speed-on-demand / movement powers in the modern world.

**Comment by emersonrp** [comment]
My intent is to start, at least, by making the player pick a main travel power per-movement-type, with the thought that there are few use cases for wanting to bind both "Flight" and "Mystic Flight" as flying powers;  ditto for "Super Speed" and "Speed of Sound", and "Super Jump" and "Mighty Leap", but I could be convinced otherwise.

**Comment by emersonrp** [comment]
I have just added a movementpowers-alpha-0.1 prerelease that incorporates these changes.  Please check it out and report back when you get a chance.

**Comment by emersonrp** [comment]
Released a version 0.11 that contains a version of support for these powers, so I'm closing this.  If the support for them wants changing, reopen this, or open a new ticket.
