### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by JamzTheMan** [emersonrp/bindcontrol#10]
On Windows 11, both Edge and Chrome won't download due to virus detection. Oddly enough, I'm able to download the .exe ok (after ignoring warning) but edge just refuses to download the zip...

![image](https://github.com/emersonrp/bindcontrol/assets/8051654/897c190f-dd92-4090-a28e-0e83606b7c44)

**Comment by emersonrp** [comment]
This is irritating and upsetting.  So, I am experiencing the same thing with Win11 Chrome and Edge.

I use Firefox mostly, which will download it fine, so I hadn't noticed this issue.  If I do download it with Firefox, right-clicking it and running Windows Defender on it works fine and comes up clean.  Uploading it to https://virustotal.com, which checks it against 60+ antivirus vendors, gives a nearly-clean rating, with a single vendor, Ikarus, flagging it as a possible trojan.  I've done a complete scan of the laptop I'm using to build and it's clean.

I am 100% confident that Edge and Chrome are misbehaving and triggering false positives in a way I don't yet understand.

The question is what to do about it.  I'm investigating this and I hope to find a solution ASAP because this is embarrassing.  I will update this issue as I know things.  Interestingly, I'd just changed build schemes a couple of minor revs ago to -avoid- malware misdetection, so this is, again, upsetting.

Thanks for the report.  I am on it.

**Comment by emersonrp** [comment]
When you get a chance, please try the BindControl-v0.13.3-windows-test.zip file that is uploaded to the release page, and let me know your luck.  Edge and Chrome will download it for me on Win11, and it doesn't trip up Windows Defender (apart from the normal "this is unsigned" warning), so this might be a path forward.  VirusTotal gives it a slightly worse score, so some antiviruses might still trigger, but it is hopefully at least downloadable.

Thanks, please let me know when you get a chance.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.13.3

**Comment by JamzTheMan** [comment]
Nice! Yes, I can download the test zip without issue, no warnings, and able to just unzip and run without Windows 11 complaining! 

Appreciate all the work, I know it can be a pain to create OS executables without all the fancy tools and certs. :)

**Comment by emersonrp** [comment]
Excellent!  I'm going to be using this packaging method going forward and we'll see.  It still triggers a couple of the more obscure antimalware vendors on the totalvirus test, but Edge and Chrome seem happy with it, as well as the major players like Windows Defender and Avast and so forth.  I'm going to close this issue, but please re-open it or start a new one if you have any further trouble starting with v0.13.4.  Thanks again and sorry for the hassle.
