### ISSUE TITLE
"Start Chat" bind broken

### ISSUE THREAD

**Issue by Fyrhtu** [emersonrp/bindcontrol#2]
Currently, if the Typing Notifier box is checked, the bind for Start Chat is ends with "beginchat " - which doesn't work. I'd likely want to replace that with "startchat" since we're not feeding the command any text to enter into the new chat.

**Comment by emersonrp** [comment]
Sorry for the long delay.  I've uploaded a partial fix to this.

It's a little bit more complicated than just the quick change because I also need to support the custom chat colors, which need "beginchat" to push in the color strings, conditionally.  Now the "beginchat" / custom color path isn't working perfectly with Linux+wine, but I'm going to check it out on Windows shortly and see there.

In any case, the current git version uses "startchat" if custom colors are not selected.  I'll make a release at some point soon.

**Comment by emersonrp** [comment]
This change went out in an earlier release, but I'm leaving this issue open for the moment.  Please check it out if you get a chance and let me know

**Comment by emersonrp** [comment]
I'm going ahead and closing this.  Please re-open it with a comment if you're still having trouble.
