### ISSUE TITLE
Misc Binds for different /slash commands

### ISSUE THREAD

**Issue by autobotcoop** [emersonrp/bindcontrol#30]
- [Buff Filtering](https://forums.homecomingservers.com/topic/4887-advanced-buff-bar-filtering/)
- visscale 8 dofweight fsaa selection menu
- Attribute Monitor Selection Menu

**Comment by emersonrp** [comment]
I've been playing this game on and off since release and had never seen that buff filtering notion before.  That's fantastic.  Yes, I'm totally on board with adding that in the short to medium term.

The other two also seem easy enough.  BindControl already does optional visscale twiddling as part of the movement powers, but there's plenty of room to expand that (and other graphics controls like dofweight and fsaa) into a more general scheme for direct binding.

They would probably be part of PowerBinder, which is to say, live in the Custom Binds panel.  People could add them as part of Simple or Complex Binds.  I'll have to build a UI for them, which is not (as we might have noticed) my strong suit, but I'm game to try.

Thanks for the suggestion!

**Comment by emersonrp** [comment]
Had a bit of a burst of inspiration last night and implemented the buff filtering as a possible PowerBinder step, which I've released as 0.17.4.  I haven't tested it fantastically rigorously, but it does seem to make binds that are formatted correctly.  Check it out!

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.4

The others will happen soonish, too, I imagine.

A question -- there's no slash command way, with the Attribute Monitoring Window, to say "stop monitoring everything" and there's no trivial way to keep state inside the keybinds themselves about what's being monitored.  I guess I'm just going to have to allow for /monitorattribute and /stopmonitorattribute with specific lists of attributes, and leave it to the user to bundle up keybinds that set the window into the desired states.  Does this seem like a reasonable implementation?

**Comment by autobotcoop** [comment]
Yeah that's what I was thinking. Some kind of drop down or something where people could select the attributes they wanted to monitor and the program would generate the necessary bind. 

I am not a programmer or UI designer. I'm just a silly sys admin with lots of ideas, but maybe we can work together on figma to design some kind of UI if that would help.

**Comment by emersonrp** [comment]
I've just released v0.17.5, which adds in a Graphics Settings option to PowerBinder, offering the slash command you mention and a couple of other ones I threw in for good measure.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.5

**Comment by emersonrp** [comment]
Version 0.17.6 adds in Attribute Monitor support to PowerBinder.  Check it out.

https://github.com/emersonrp/bindcontrol/releases/tag/v0.17.6

**Comment by emersonrp** [comment]
I'm going to go ahead and close this one since all of the original request has been implemented.  Please re-open if you have any trouble with any of the stuff referenced here.
