### ISSUE TITLE
MM pets do not "remember" chattiness after a reset.

### ISSUE THREAD

**Issue by xizar** [emersonrp/bindcontrol#76]
Given the frequency with which it is necessary to run "reset.txt" to fix SoD issues, it would be nice if some other toggles would be respected.

Alternately, perhaps chattiness could have a default state built in.  (mostly I just want them to shut up, but occasionally I need them to talk so I can keep track of them.)

**Comment by emersonrp** [comment]
The latter is much much easier to implement -- having reset honor the current state of chattiness would involve having two reset files that got toggled between when chattiness got toggled, which is -possible- but way way fiddly since the reset file is created collaboratively in lots of places throughout the code, and each of those would need to be touched to build the second one, also.  And then we have code sprinkled throughout the app being aware of the Mastermind-related configuration which seems like bad separation of concerns.  Thinking this through, still, though.  Having one or the other be the default state on reset, and being able to choose which it is, seems much more likely and simple.

**Comment by emersonrp** [comment]
Implemented a "chatty is default" checkbox on the mastermind page, which seems to be working correctly to my initial testing.  Check it out:

https://github.com/emersonrp/bindcontrol/releases/tag/v0.21.3

**Comment by xizar** [comment]
Seems fine on my end.
